- pom.xml
* Moved filtering of resources out of run-its maven profile because this filtering is needed not just for integration tests
```bash
$ mvn clean install -e -DskipTests && mvn clean verify -e -Prun-its artifact:buildinfo -Dreference.repo=central
...
[INFO] --- maven-artifact-plugin:1.0-SNAPSHOT:buildinfo (default-cli) @ maven-ear-plugin ---
[WARNING] SCM source tag in buildinfo source.scm.tag=HEAD does not permit rebuilders reproducible source checkout
[INFO] Saved info on build to xxx...\maven-ear-plugin\target\maven-ear-plugin-3.1.1-SNAPSHOT.buildinfo
[INFO] Checking against reference build from central...
[WARNING] Reference buildinfo file not found: it will be generated from downloaded reference artifacts
[INFO] Reference build java.version: 1.8 (from MANIFEST.MF Build-Jdk-Spec)
[INFO] …
```
> [MEAR-286] Maven project enhancement

- src/main/java/org/apache/maven/plugins/ear/AbstractEarMojo.java
> Replace typo "ben" with "been" in AbstractEarMojo.java

- src/main/java/org/apache/maven/plugins/ear/EarMojo.java
[MEAR-293] - skinnyModules option working even if skinnyWars option is turned off (or has default value).
> [MEAR-293] skinnyModules to work even if skinnyWars is false

- src/main/java/org/apache/maven/plugins/ear/util/JavaEEVersion.java
- src/test/java/org/apache/maven/plugins/ear/util/JavaEEVersionTest.java
> compareTo should throw NullPointerException per spec

- pom.xml
> update ejb plugin

- src/main/java/org/apache/maven/plugins/ear/ApplicationXmlWriter.java
- src/main/java/org/apache/maven/plugins/ear/util/JavaEEVersion.java
- src/test/java/org/apache/maven/plugins/ear/it/EarMojoIT.java
- src/test/resources/projects/project-100/expected-META-INF/application.xml
- src/test/resources/projects/project-100/pom.xml
Added support for JakartaEE10 (based on the previous commit for JakartaEE9). Issue: [https://issues.apache.org/jira/browse/MEAR-309](https://issues.apache.org/jira/browse/MEAR-309)
> [MEAR-309] Support JakartaEE10

- src/main/java/org/apache/maven/plugins/ear/GenerateApplicationXmlMojo.java
https://rules.sonarsource.com/java/RSPEC-2116
-----
To make clear that …
> (doc) Remove not helpful debug log

- pom.xml
- src/test/java/org/apache/maven/plugins/ear/it/AbstractEarPluginIT.java
- src/test/resources/projects/project-089/pom.xml
- src/test/resources/projects/project-090/pom.xml
- src/test/resources/projects/project-091/pom.xml
- src/test/resources/projects/project-092/pom.xml
- src/test/resources/projects/project-093/pom.xml
- src/test/resources/projects/project-094/pom.xml
- src/test/resources/projects/project-097/pom.xml
- src/test/resources/projects/project-098/pom.xml
- update in project pom
- update in it tests
---
To make clear that you …
> [MEAR-311] Require Java 8

- pom.xml
- src/main/java/org/apache/maven/plugins/ear/EarMojo.java
- src/test/java/org/apache/maven/plugins/ear/it/AbstractEarPluginIT.java
> Upgrade Maven Verifier to 2.0.0-M1

- pom.xml
> [MEAR-318] Require Maven 3.2.5

- src/main/java/org/apache/maven/plugins/ear/EarMojo.java
> [MEAR-319] Remove generated MANIFEST from outdatedResources

- pom.xml
- src/it/MEAR-243-skinny-wars-provided/ear-module/pom.xml
- src/it/MEAR-243-skinny-wars-provided/verify.bsh
- src/it/MEAR-243-skinny-wars-provided/war-module-one/pom.xml
- src/it/MEAR-243-skinny-wars-provided/war-module-two/pom.xml
- src/it/filenamemapping-usage-fail/ear-module/pom.xml
- src/it/filenamemapping-usage-fail/war-module/pom.xml
- src/it/non-skinny-wars/ear-module/pom.xml
- src/it/non-skinny-wars/verify.bsh
- src/it/non-skinny-wars/war-module/pom.xml
- src/it/packaging-excludes/pom.xml
- src/it/packaging-excludes/verify.bsh
- src/it/packaging-includes/pom.xml
- src/it/packaging-includes/verify.bsh
- src/it/skinny-wars-filenamemapping-full/ear-module/pom.xml
- src/it/skinny-wars-filenamemapping-full/verify.bsh
- src/it/skinny-wars-filenamemapping-full/war-module/pom.xml
- src/it/skinny-wars-filenamemapping-no-version/ear-module/pom.xml
- src/it/skinny-wars-filenamemapping-no-version/verify.bsh
- src/it/skinny-wars-filenamemapping-no-version/war-module/pom.xml
- src/it/skinny-wars-javaee5/verify.bsh
- src/it/skinny-wars-javaee5/war-module3/pom.xml
- src/it/skinny-wars-timestamp/ear-module/pom.xml
- src/it/skinny-wars-timestamp/verify.bsh
- src/it/skinny-wars-timestamp/war-module-one/pom.xml
- src/it/skinny-wars/ear-module/pom.xml
- src/it/skinny-wars/verify.bsh
- src/it/skinny-wars/war-module/pom.xml
- src/test/resources/projects/project-092/pom.xml
> [MEAR-304] Update dependencies used in IT tests

- src/main/java/org/apache/maven/plugins/ear/EarMojo.java
- src/test/java/org/apache/maven/plugins/ear/it/AbstractEarPluginIT.java
- src/test/java/org/apache/maven/plugins/ear/it/EarMojoIT.java
- src/test/resources/projects/project-101/expected-META-INF/application.xml
- src/test/resources/projects/project-101/pom.xml
> [MEAR-301] fix repackaging when defaultLibBundleDir beginning with dot

- pom.xml
- src/it/skinny-wars/war-module/pom.xml
- src/main/java/org/apache/maven/plugins/ear/AbstractEarMojo.java
- src/main/java/org/apache/maven/plugins/ear/EarMojo.java
- modules will not be unpacked and packed again
- changes in module archive will be done by ZipFileSystem
---
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
> [MEAR-298] Improving EAR packaging use FileSystem instead of repackaging

- src/site/xdoc/download.xml.vm
> Refresh download page

- src/main/java/org/apache/maven/plugins/ear/AbstractEarMojo.java
- src/site/apt/examples/customize-file-name-mapping.apt.vm
- src/site/apt/index.apt.vm
> [MEAR-321] Remove not implemented parameter - useBaseVersion

- src/main/java/org/apache/maven/plugins/ear/AbstractEarMojo.java
- src/main/java/org/apache/maven/plugins/ear/util/JavaEEVersion.java
> Add supported versions to plugin documentation

- .github/release-drafter.yml
- .github/workflows/pr-automation.yml
- .github/workflows/release-drafter.yml
- .github/workflows/stale.yml
Plugin has only master branch, so simple release-drafter
> Add release-drafter, PR-automation and stale action

- pom.xml
- src/test/java/org/apache/maven/plugins/ear/it/AbstractEarPluginIT.java
Including fixes dependabot (PR #134) can't do.
> Update Parent to 44

- src/main/java/org/apache/maven/plugins/ear/EarMojo.java
- src/main/java/org/apache/maven/plugins/ear/GenerateApplicationXmlMojo.java
> Reduce log noise
